### ISSUE TITLE
The dreaded Vault 15 rope bug (iPad)

### ISSUE THREAD

**Issue by Sztokholm** [alexbatalov/fallout1-ce#115]
The game crashes 100% of the time when I install the 2nd rope in Vault 15 in order to descend to level -2.
The crash happens only when I use the rope from weapon bar. If I right click, pick „use from inventory” and click on the shaft „it does nothing…”
I use 1.0.0 release on iPad. Can provide the save if someone helps me out in getting it out from the iPad.
I wanted to use the debug version but they’re all expired.

**Comment by alexbatalov** [comment]
Thanks for patience, download latest release.
