### ISSUE TITLE
Fast metabolism not decreasing resistances

### ISSUE THREAD

**Issue by Northfear** [alexbatalov/fallout1-ce#12]
During character creation fast metabolism trait is increasing radiation and poison resistance instead of setting them to 0% (or decreasing?)
![1](https://user-images.githubusercontent.com/11291116/218304779-56912f8d-ed36-4399-a351-c119c9fce867.png)

**Comment by alexbatalov** [comment]
Nice catch, this one affects both F1Ce and F2CE.
