### ISSUE TITLE
game crashes when asking tandi certain questions

### ISSUE THREAD

**Issue by garzeth** [alexbatalov/fallout1-ce#120]
i arrived at shady sands and talked to the other characters .when i talked to tandi and ask questions...example: like what going on around these parts? the game would crash...but when i ask other questions it just plays normally...is this a bug or my game files are broken/missing something....

**Comment by garzeth** [comment]
i read a issue related to this but the debug versions that solve this issue are already expired

**Comment by bit-hack** [comment]
Could you post a little more information to help reproduce your issue:
- What fallout-ce release were you running?
- What OS are you running on?
- Where did you download your fallout game files from?

**Comment by garzeth** [comment]
i am using the fallout ce version 1.0 release from github and running it on a android 8.1 oreo os...and my game files are a backup copy from a friend..

**Comment by garzeth** [comment]
and it also goes for aswell with the vita version....

**Comment by alexbatalov** [comment]
Thanks for patience, download latest release.
