### ISSUE TITLE
Fade issue with first aid. Understand it is fixed, but no debug builds are available only version 1.0. 

### ISSUE THREAD

**Issue by rcaruso90** [alexbatalov/fallout1-ce#129]
Need help either obtaining a more recent build or advice on how to build from source on Mac OS.

**Comment by rcaruso90** [comment]
Update: i did some googling and figured out using cmake to build an xcode project and then compile from there. got it up and running and the first aid bug is fixed. I'm only not closing the issue in the hopes someone sees this and releases newer builds with this issue fixed. 

Thank you very much to everyone who contributed to this project as it's really cool to get to experience this game for the first time.

**Comment by forb1d** [comment]
could you please get a bit more detailed info re "using cmake to build an xcode project and then compile from there"
I can't even understand what to google! sorry for the naive question!

**Comment by alexbatalov** [comment]
Thanks for patience, download latest release.

**Comment by rcaruso90** [comment]
> @rcaruso90 could you please give a bit more detailed instructions re "using cmake to build an xcode project and then compile from there" I can't even understand what to google! sorry for the naive question!

No need anymore with the latest release!
