### ISSUE TITLE
Disable MacOS exclusive fullscreen mode

### ISSUE THREAD

**Issue by radozd** [alexbatalov/fallout1-ce#13]
Hi,
First of all. It's WOW!

In the future updates I'd like to be able to use gestures and easily switch between apps while playing Fallout.
It's not possible right now as far as I can see.

Thanks in advance

**Comment by alexbatalov** [comment]
You can run it in windowed mode - create `f1_res.ini` in your Fallout directory:

```ini
[MAIN]
SCR_WIDTH=1280
SCR_HEIGHT=720
WINDOWED=1
```

Right now it has it's own drawbacks (capturing mouse pointer), but you'll be able to easily Cmd-Tab to other apps.

**Comment by radozd** [comment]
Good one. Thanks!
