### ISSUE TITLE
New release breaks inventory on touch screens

### ISSUE THREAD

**Issue by Pants98** [alexbatalov/fallout1-ce#134]
V1.1.0 improved the touch controls but they created a problem with the inventory where items can no longer be dragged. The item can be selected but then it's instantly dropped. This seems to be an oversight with the tap = click functionality of the touch controls, where touching the screen and dragging it simply moves the cursor while tapping clicks the item but doesn't allow the click to be held

**Comment by alexbatalov** [comment]
I've just checked in on the iPhone, it works as expected - position cursor over the item in inventory, long press until item is lifted, move to proper slot. Will check on Android a bit later.

**Comment by Pants98** [comment]
You're right! I never bothered to hold the item for more than a second! Wow, I'm dumb 😅
Sorry if I wasted your time. Thank you very much for the new release, also. It's so much better to not have to frantically tap the screen everytime I want to do something.
