### ISSUE TITLE
Full screen-Mac

### ISSUE THREAD

**Issue by ninonook1** [alexbatalov/fallout1-ce#135]
i am unable to use fullscreen, it appears that the game runs on a window and it doesnt seem like there is a way to put it into fullscreen, or zoom in the window to fit the screen fully.

**Comment by alexbatalov** [comment]
Hey there, you can use `f1_res.ini` to set resolution and switch between fullscreen/windowed mode (see Configuration section in readme):

```ini
[MAIN]
SCR_WIDTH=1280
SCR_HEIGHT=720
WINDOWED=0
```
