### ISSUE TITLE
Cannot Save Game in IOs

### ISSUE THREAD

**Issue by cwalker912** [alexbatalov/fallout1-ce#137]
Hello and thank you for this port.

### Issue
The following error is provided when trying to save game: 
 "Error saving game! Unable to save game."

### Platform
Ipad pro 12.9 v3 running iPadOS v 17.3.1; Fallout 1 was purchased from GOG and sideloaded via sideloady. File names were converted to lowercase

### Other info
If a savegame file is copied to the ipad it can be loaded within the game. If an attempt is made to overwrite the save slot within the game the previous save is deleted, and the slot is shown as empty. I have tried changing the permissions of all files and folders to rwxrwxrwx and get same error. 

Thanks!!

**Comment by gllmAR** [comment]
I had the same problem on raspberry pi (GOG install, unable to save game dialog, folder SLOT0X was created but had no content inside)

Renaming folder DATA to data and SAVEGAME to savegame did solve my problem, now I can save and reload game.

**Comment by cwalker912** [comment]
Thank you so much for the response! I confirm this resolved the issue for me as well.
The following are lowercase:
critter.dat
f1_res.ini
fallout.cfg
master.dat
data/
data/savegame

other subfolders in data/ are still in all capital letters
