### ISSUE TITLE
Mac OS X. Could not find the master datafile

### ISSUE THREAD

**Issue by wellbry** [alexbatalov/fallout1-ce#151]
I made sure that the case in fallout.cfg matched with the file system but it still won't launch.
Any ideas?

**Comment by demirozg** [comment]
Could you send an image of your Fallout folder that contains the Fallout Community Edition application?

**Comment by wellbry** [comment]
Sure
![Screen Shot 2024-04-20 at 16 42 40](https://github.com/alexbatalov/fallout1-ce/assets/56337196/d2841d67-e2db-42a1-95e8-d3fd273c56fa)

**Comment by alexbatalov** [comment]
Hey, the folder itself looks good. Post your `fallout.cfg`, I bet there is something with paths. Or just delete it, the game will recreate this file from defaults. BTW you have `fallout-ce.app`, which is a previous version. Download latest release, it was renamed to `Fallout Community Edition`.

**Comment by wellbry** [comment]
Huh. Well the newer release works
Thanks!
