### ISSUE TITLE
[Android] .apk file missing

### ISSUE THREAD

**Issue by machinateddesigns** [alexbatalov/fallout1-ce#16]
I've searched the whole repository, and I can't find the apk file talked about in the readme anywhere. Was it removed, or is it to be found elsewhere?

**Comment by machinateddesigns** [comment]
I think I may have finally found the APK in the actions tab. Sorry for the bother.

**Comment by alexbatalov** [comment]
See [Releases](../releases) page, the one from [Actions](../actions) tab contains Debug builds intended for testers. From Android standpoint these debug and release versions are different apps, so both require game assets and have separate savegames.
