### ISSUE TITLE
IOS won't Save Game

### ISSUE THREAD

**Issue by zaknafien44** [alexbatalov/fallout1-ce#168]
iOS won't save game. Running OS17.4.1 on 15 Pro 
Loaded game with Sideloady. Opened and got the error needed. 
Moved over the master.dat, critter.dat, and data folder to the Fallout app through Sideloady. 
Run game and works great. Items, movement and story all work great. Even previous saved filed are seen by the game but when I go to save a new game or over write I get " Error saving game! Unable to save game. " popup. 

Tried adding and removing various files and configs to no effect.

**Comment by regulgul** [comment]
I have solution. Copy only master.dat and critter.dat using finder/itunes. Don’t copy data folder. 
Now you can save game

**Comment by zaknafien44** [comment]
That worked. Did a fresh re-instal and that did it. Thank you
