### ISSUE TITLE
build for arm64 linux

### ISSUE THREAD

**Issue by albsen** [alexbatalov/fallout1-ce#183]
Hi, currently the build instructions are not referencing arm64

Here are the steps I used to build it on arm64 debian linux for others that might be interested:

```
sudo apt install cmake libsdl2-dev zlib1g-dev
cmake -B build -D CMAKE_BUILD_TYPE=RelWithDebInfo
cmake --build build -j $(nproc)
```

Compiling works, I've also checked the intro video, it's working - has some artifacts.
Started the game, played for 5 minutes. All looks good so far.

**Comment by hippydave** [comment]
[This commit](https://github.com/Northfear/fallout1-ce-vita/commit/00c1269db7d69ae86ee6211a9e8c77548d002b09) fixes the video artifacts. glhf

**Comment by albsen** [comment]
Thx - will apply that patch.

I've also needed this patch to make save work with my all caps DATA folder.

https://github.com/alexbatalov/fallout1-ce/commit/aa3c5c1e3e3f9642d536406b2d8d6b362c9e402f.patch

```
From aa3c5c1e3e3f9642d536406b2d8d6b362c9e402f Mon Sep 17 00:00:00 2001
From: aidan <aidan.dodds@googlemail.com>
Date: Sat, 18 Nov 2023 21:05:54 +0000
Subject: [PATCH] Ensure db_findfirst path is resolved

---
 src/plib/db/db.cc | 1 +
 1 file changed, 1 insertion(+)

diff --git a/src/plib/db/db.cc b/src/plib/db/db.cc
index 3ddfd20..734b94e 100644
--- a/src/plib/db/db.cc
+++ b/src/plib/db/db.cc
@@ -2575,6 +2575,7 @@ static int db_findfirst(const char* path, DB_FIND_DATA* findData)
     char basePath[COMPAT_MAX_PATH];
     compat_makepath(basePath, drive, dir, NULL, NULL);
 
+    compat_resolve_path(basePath);
     findData->dir = opendir(basePath);
     if (findData->dir == NULL) {
         return -1;
```
