### ISSUE TITLE
IPA file for IOS installation missing

### ISSUE THREAD

**Issue by sinistarhascome** [alexbatalov/fallout1-ce#186]
Apologies if I am simply installing this incorrectly but I do not believe the fallout-ce.ipa file that the ios installation requires is not available in the install files and I am not sure how to install it onto my iPhone without it.

**Comment by dje4321** [comment]
I am not sure what your question is asking as the english is very gibbered. 

Youll need to download the iOS .ipa file from the releases folder and follow the Readme for how to manually push the game data files onto the device. Important to note that you will have to run the app atleast once to push the game files into the application. 

![image](https://github.com/alexbatalov/fallout1-ce/assets/10913120/56137e11-53b6-4cd3-9cd9-774f31ee86f6)

**Comment by sinistarhascome** [comment]
I understand what I need to do, what I am saying is that I can't find the iOS .ipa file that the instructions are referring to, it is not in the available files

**Comment by dje4321** [comment]
Ah. Its under the releases section

https://github.com/alexbatalov/fallout1-ce/releases/tag/v1.1.0

https://github.com/alexbatalov/fallout1-ce/releases/download/v1.1.0/fallout-ce-ios.ipa (Direct Link)

**Comment by sinistarhascome** [comment]
thanks!

**Comment by dje4321** [comment]
If this resolves the issue, please close the issue. Thanks
