### ISSUE TITLE
[android, gog]  game crashes when speaking with Tandi

### ISSUE THREAD

**Issue by VaultDweller13** [alexbatalov/fallout1-ce#20]
Android 10
If I choose 'What else is around these parts?' or 'Have you heard any stories from down south?' lines, game crashes.
If I choose other dialogue options, then end the conversation, any other attempts to just talk to her make the game crash.
  
Tried release and debug versions.

**Comment by alexbatalov** [comment]
Savegame?

**Comment by VaultDweller13** [comment]
> Savegame?
[SLOT02.zip](https://github.com/alexbatalov/fallout1-ce/files/10720023/SLOT02.zip)

**Comment by alexbatalov** [comment]
Works fine on macOS and iOS, but indeed crashes on Android as soon as dialog starts. Will investigate, thanks for report.
