### ISSUE TITLE
Window scalling on iOS

### ISSUE THREAD

**Issue by WastelandMyx** [alexbatalov/fallout1-ce#21]
Hello,
First of all, this is amazing job, I’ve been waiting for old fallout Mobile version for ages and now dream came true, thank You very much!

Only issue I have with iOS version is lack of window scalling - when I opened the game for a first time window was about 3/4 size of a full screen, and when I re-opened it next day it was only 1/2. On both cases, scalling button only downsized tej original dimensions. Is there a chance that could be fixed anyhow? Sorry if that’s a noobish question, I’m not a coder.
Unit I ma using is iPad 9 (10.2 inch) with 15.6.1 iOS if that makes a difference.
Regards,
Myx

**Comment by alexbatalov** [comment]
The default window size is 640x480, which is scaled to your screen size. Create a new file `f1_res.ini` and drop it to the Fallout app like you did with game assets:

```ini
[MAIN]
SCR_WIDTH=1080
SCR_HEIGHT=810
```
