### ISSUE TITLE
[Feature Request] something akin to high resolution patch

### ISSUE THREAD

**Issue by powerpuffboysz** [alexbatalov/fallout1-ce#23]
would it be possible to add something akin to the "high resolution patch" for the vanilla engine to this to unstretch 4:3 assets and show more of the ingame map at once on pcs/macs?

**Comment by alexbatalov** [comment]
Create `f1_res.ini`:

```ini
[MAIN]
SCR_WIDTH=1280
SCR_HEIGHT=720
WINDOWED=1
```

**Comment by powerpuffboysz** [comment]
thank you. maybe put this in a more easy to find spot because im positive i wont be the last looking for info as any info on the ce ports of fallout 1 and 2 are pretty sparse
