### ISSUE TITLE
IOS: Fallout not detecting master.dat, critter.dat and data folder (AltStore)

### ISSUE THREAD

**Issue by VirgilRex** [alexbatalov/fallout1-ce#25]
I just installed Fallout via AltStore using the last ios release saved on my iphone local folders. (AltServer was running too)

When I launched the game instead of what readme suggested, a window box opened with the text that it could not open the game. [pic](https://imgur.com/a/tKPmQtu)
But I checked and Fallout started to appear on the shared files section on iTunes. I loaded the proper files and reloaded. still the same box as before.

[Here is the proof that the files are inside](https://imgur.com/a/4JI80sx), I tried opening and closing (properly) everything. I tried turning off and on the iPhone, and iTunes too to make sure the files were in place. Still nothing.

**Comment by alexbatalov** [comment]
Make sure `master.dat`, `critter.dat` and `data` folder are all lowercased before copying to iPhone.

**Comment by VirgilRex** [comment]
After renaming the files to all lowercase (including file extensions) it is working properly
[Picture](https://imgur.com/a/GPsxCW3)
