### ISSUE TITLE
[IOS] ipad pro 11 2018 streched text cant read well in game green letters

### ISSUE THREAD

**Issue by tonnocometa** [alexbatalov/fallout1-ce#29]
first of all amazin job portaing this masterpiece but im having a problem reading the green text in all of the game, i updated the f1_res.ini file in the game and i setted the specs like this, but the texture seems streched at the point i cant properly read, also in 1190x834 i have still room for zooming the game
![image](https://user-images.githubusercontent.com/125415659/219019177-706837e1-e533-48bd-839b-c03599e7779d.png)
![image](https://user-images.githubusercontent.com/125415659/219019388-0731ec8d-cb6a-406c-b930-d5f84f1259f2.png)
![IMG_0097](https://user-images.githubusercontent.com/125415659/219019820-ff57f28c-5d69-41c0-ac35-969c0fd6f277.PNG)

**Comment by tonnocometa** [comment]
So what should I do now?

**Comment by tonnocometa** [comment]
Sorry, I feel very dumb but I never compiled the game myself and I really don’t know what a Xcode is, I used AltStore/alt server to install fallout 1 ce for iOS (I didn’t find a iPadOS version) and then used my steam file to upload the game file.. so still no idea why iPad recognize this game as an iPhone app only…

**Comment by ekotov1986** [comment]
I have exactly the same problem on Ipad 10.2. Never compiled anything, just followed installation instructions.

**Comment by alexbatalov** [comment]
Will check, stay tuned.

**Comment by pashlya** [comment]
Actually, this is a question, where's an Xcode project in the sources. I just see a cmake guidelines, and they compile into a macOS binary.

**Comment by alexbatalov** [comment]
Hey folks, this problem is resolved. Download latest debug build, resign as usual with AltStore/Sideloadly. Do not set `WINDOWED` in your `f1_res.ini` (if you do status bar will be visible).
