### ISSUE TITLE
MacOS/iOS - No music

### ISSUE THREAD

**Issue by mutantant** [alexbatalov/fallout1-ce#3]
Music doesn't seem to be playing in MacOS or iOS for fallout1-ce (though it does work fine, at least on MacOS, for fallout2-ce). Audio, inventory sounds, attack sounds, all work, but no music at all, from the main menu on to in-game, travel map, etc.

I'll be trying the Windows version soon to see if that has music, but for sure no music on the Apple side of things for me. Tried checking paths, cfg files, in-game settings, and testing if capital letter file names were causing issues (see the other issue involving case-sensitive files systems and master.dat/critter.dat, which I had to rename to all lower-case to get to work), but no changes seemed to help.

(edited to add, no music for fallout2-ce under iOS either, but the music for that version works fine under MacOS. I'll add that to an issue over in that repo, just putting this here for clarification)

MacOS 13.2 (22D49), Silicon, and iPadOS 15.7.1 sideloaded with AltServer, via downloaded pre-built release versions of fallout1-ce.

**Comment by alexbatalov** [comment]
The engine does not handle case-sensitive paths properly. Check `fallout.cfg`, your `music_path1` should be either relative or absolute path with correct case (I have `music_path1=/Users/alex/Desktop/Fallout/sound/music/`). Note that `sound/music/` can actually be either inside `data` or not. Will check on iOS later.

**Comment by mutantant** [comment]
> The engine does not handle case-sensitive paths properly. Check `fallout.cfg`, your `music_path1` should be either relative or absolute path with correct case (I have `music_path1=/Users/alex/Desktop/Fallout/sound/music/`). Note that `sound/music/` can actually be either inside `data` or not. Will check on iOS later.

Swapping the default "\" with the *nix "/" did the trick on MacOS, but no change on iOS.

**Comment by alexbatalov** [comment]
The problem is the same - bad paths. The temporary solution is also the same. Download `fallout.cfg` from iPhone to Mac. Open with any text editor, most likely you will have `music_path1=sound\music\`. Change it accordingly (I have `music_path1=sound/music/`), copy `fallout.cfg` back to iPhone.

**Comment by bencarr1337** [comment]
I am having with the music on iOS as well. I've changed the paths and tried every combination. I'm going from PC - IOS and the folders are uppercase. 

music_path1=sound/music/
music_path1=data/sound/music/
music_path1=data/SOUND/MUSIC/
music_path1=SOUND/MUSIC/

**Comment by bencarr1337** [comment]
Is there any way to use items while in the inventory menu. I couldn't figure out how to use Stimpacks from the inventory?

**Comment by alexbatalov** [comment]
The thing is that there are different Fallout distributions, some of them have filenames lowercased, some uppercased, in some `sound/music/` is located inside `data` (your case), some not. Here is my minimal setup (based on v1.1, you can also have `data` with a bunch of files if you're using assets from v1.2):
<img width="832" alt="fallout-folder-hierarchy-mac" src="https://user-images.githubusercontent.com/172978/218260977-f9dc7049-2de1-4745-9009-2d167c387460.png">

Here is `fallout.cfg`, it's universal (macOS and iOS). Don't forget to rename as GitHub does not like `cfg` extension.
[fallout.txt](https://github.com/alexbatalov/fallout1-ce/files/10713770/fallout.txt)

**Comment by mutantant** [comment]
I've double and triple checked, tried all the combos of folders, yet no music on iOS.

File structure:
data/sound/music/
All lower case.
Ini file: 
music_path1=data/sound/music
music_path2=sound/music (I add this just to test, no change)

Music files: all upper case, data/sound/music/01HUB.ACM

Still no music anywhere in iOS.

**Comment by alexbatalov** [comment]
Missing trailing slash?
```
music_path1=data/sound/music/
```

**Comment by mutantant** [comment]
> Missing trailing slash?
> 
> ```
> music_path1=data/sound/music/
> ```

So sorry, no, I simply forgot to type it in to the report (I am typing on a different machine than the one which I have been transferring the fallout.cfg file back and forth to and from iOS on, so copy/paste was not an option).

music_path1=data/sound/music/ is exactly as it exists on the iPad, and I just copied it back to the machine to double check.

music=1 as well (so it's not disabled via the menu).

Is the music working for you in your tests, if you have an iOS device? If it is for you and not me, I wonder if it's a file format issue or something. The data comes directly from a clean GoG install.

Or is it possible it's a line feed issue? I mean, the other options seem to read fine, but perhaps the DOS/Windows linefeed is causing an issue with reading entries in certain parts.

**Comment by alexbatalov** [comment]
I've just checked GOG version on both iPhone and iPad. My GOG version has everything uppercased, so it's `MASTER.DAT`, `CRITTER.DAT`, and `DATA/SOUND/MUSIC`. It comes with bundled `fallout.cfg` that has all paths lowercased:

```ini
music_path1=data\sound\music\
music_path2=data\sound\music\
critter_dat=critter.dat
critter_patches=data
master_dat=master.dat
master_patches=data
```

For the first test I've copied uppercased game assets and modified `fallout.cfg` accordingly:

```ini
music_path1=DATA/SOUND/MUSIC/
music_path2=DATA/SOUND/MUSIC/
critter_dat=CRITTER.DAT
critter_patches=DATA
master_dat=MASTER.DAT
master_patches=DATA
```

For the second test I took your `fallout.cfg` and lowercased filenames before copying to iPad.

In both tests music is playing. There is no music in the main menu due to mixed case lookup, but when you start new game or loading it's there.

**Comment by mutantant** [comment]
Ok, so all in all, I'll close this out.

I went and changed ALL files to uppercase via a recursive find/rename command. All files, all folders, are upper-case, and all config options relating to folders and files are upper-case, with "/" instead of "\\", and all seems to be working.

This is always going to be a pain in your butt, so I guess if you could translate the paths and filenames internally, it would make things easier, becuse I can see you are going to get a million issues opened about this otherwise. It seems every version, every fan-patch, and every mod is going to BeAlLoVeRtHePlAcE with caps since Fallout has always lived on the case-insensitive Microsoft drive formats.

For those who come after, here is the answer:

1. Change all files and folders to upper-case. MASTER.DAT, CRITTERS.DAT, DATA, etc.
2. Change file-based settings in the cfg file, fallout.cfg, to upper-case AND if you are trying for iOS change all the DOS/Windows style directory dividers ("\") to Unix style ("//"), as you can see in the above post by @alexbatalov .
3. *Don't*, at this point, copy f1_res.ini over to the iOS device, since it will just mess with the size of the game on the screen, even if you change the resolution in that file.

Thanks for the help, @alexbatalov , and keep up the great work!
