### ISSUE TITLE
Unable to get proper fullscreen with Pixel 3 (Fallout 1 from Epic Store)

### ISSUE THREAD

**Issue by Greg7000** [alexbatalov/fallout1-ce#31]
I am able to get the game running. However, screen is kind of small. I tried changing the f1_res.ini to:
[MAIN]
GRAPHICS_MODE=2
SCALE_2X=0
SCR_WIDTH=1320
SCR_HEIGHT=480
COLOUR_BITS=32
REFRESH_RATE=0
WINDOWED=0
WINDOWED_FULLSCREEN=0
WIN_DATA=0

However no matter how much I try to change it either the screen stay small or Iit can't start. Anyone managed to change res for pixel 3 given fallout 1 (epic store installation)?

**Comment by alexbatalov** [comment]
Pixel 3 has 2160x1080 resolution, which is 2:1.

```ini
[MAIN]
SCR_WIDTH=960
SCR_HEIGHT=480
```

**Comment by Greg7000** [comment]
> Pixel 3 has 2160x1080 resolution, which is 2:1.
> 
> ```ini
> [MAIN]
> SCR_WIDTH=960
> SCR_HEIGHT=480
> ```

It worked thx
