### ISSUE TITLE
Game crashes when going for second time to vault 15

### ISSUE THREAD

**Issue by Greg7000** [alexbatalov/fallout1-ce#34]
(context: pixel3, fallout from epic store)
Went to vault 15 once and it worked. Forgot a rope so I  quit that level to get one. 

Now when I try to return to vault 15 with my rope, when I click the green arrow in the world map to enter vault 15 level, game crashes

**Comment by alexbatalov** [comment]
It's already been fixed (#27). Please use debug version or wait for update (early next week).

**Comment by Greg7000** [comment]
> It's already been fixed (#27). Please use debug version or wait for update (early next week).

What is the update procedure? Reinstall? Can you indicate the save directory so I can back them up?

**Comment by alexbatalov** [comment]
Your save games folder for release version is `/Android/data/com.alexbatalov.falloutce/files/data/SAVEGAME` and `/Android/data/com.alexbatalov.falloutce.debug/files/data/SAVEGAME` if you're running debug version. The save games are are completely interchangeable, you can copy between release/debug versions whenever you like.

The update process is exactly the same as install - download `apk` on your device, install with Android file manager. Your data folder and save games won't be affected.

**Comment by eXXe88** [comment]
Hello, I can't find the debug .apk file anywhere on this site. Just the normal .apk from realease or IDK how to download that debug file. Could someone please help

**Comment by alexbatalov** [comment]
Go to [Actions](https://github.com/alexbatalov/fallout1-ce/actions) tab, pick latest workflow, scroll down to Artifacts section.
