### ISSUE TITLE
Using ropes in Vault 15 elevators does not work

### ISSUE THREAD

**Issue by Sergorov** [alexbatalov/fallout1-ce#37]
Hello! I simply love being able to play Fallout 1 and 2 on my PS Vita. That's incredible.

**The issue:** 
1. I have the rope in my inventory and stand outside the elevator in Vault 15
2. I switch the cursor to pointer, aim for the elevator shaft and long-click to get to the interactions, where I choose my backpack and select the rope
3. it looks like it's working, the player moves to the elevator shaft and does his default "busy" animation
4. But: the rope is not attached, and the game responds with "this does nothing", hence I cannot continue.

This does not only affect the Vita version. I can reliably reproduce this issue on both elevators in vault 15 in the PC version with the 64 bit release (Feb 2023 v1.0), running it on Windows 10 (22H2). 

**Workaround:** The only way I found to get around this is to save, open Fallout with the official Steam launcher (non-ce). There it immediately worked as described in steps 1-3, but with a positive result. I saved again after attaching the rope, closed and went back to CE. But as indicated, I had to do that again for the second rope as well. 

**Side note:** Maybe there is a more general bug in using inventory objects on environment? I remember previously trying to use the lockpick-item in the raider's camp on one of the locked prison doors. It didn't work either. But at the time I just thought that was due to failing the skill check, as my lockpicking is not great. I resorted to use the skill directly a couple of times and at some point it worked. 

Keep up the great work! This is really spectacular!

**Comment by M1sh2** [comment]
I went through the moment with the rope in vault 15, I put it in the slot, select (as with weapons) and point to where the rope should be. With the problematic door at the raiders I confirm (it opens very strangely. Sometimes it's impossible to open the door where Tandi is. For some reason, it says that the door is not an object to be broken into.

This does not work through the menu:
![image](https://user-images.githubusercontent.com/59886778/220011820-ad3eb61c-007c-4baa-b04d-a71bc4060481.png)

**Comment by alexbatalov** [comment]
Scrolling with mouse wheel is fixed. Post savegame with rope stuff, I'll look into.
