### ISSUE TITLE
Fast shot doesn't decrease AP cost with unarmed/melee weapons

### ISSUE THREAD

**Issue by emxd** [alexbatalov/fallout1-ce#52]
Distribution: GOG
Behavior present in: fallout1-re master; fallout1-ce master
Platform: win11 21h2

In vanilla under fastshot:
barehanded unarmed had aiming disabled without AP cost usage decrease
unarmed/melee weapons had aiming disabled with AP cost usage decrease

In re/ce under fastshot:
barehanded unarmed has aiming disabled without AP cost usage decrease
unarmed/melee weapons have aiming disabled without AP cost usage decrease

For re, the behavior should mirror vanilla I suppose?
As far as ce is concerned, the only question would be (after fixing the AP cost of melee/unarmed weapons) whether to extend fastshot AP decrease to barehanded unarmed as well. Or instead whether to allow aiming on barehanded unarmed.

On a second thought, maybe ce should just mirror vanilla too...

**Comment by alexbatalov** [comment]
Current implementation of Fast Shot follows F2 behaviour (no aiming, cost is decreased only for weapons with range above 1). Will fix RE during reconciliation (vanilla F1 has no range restriction, cost is decreased for any weapon). I'm not sure if something needs to be done for CE.

**Comment by emxd** [comment]
I think it would be good to have ce also behave identically to vanilla to preserve the original meta and feel. Fallout1 had a build created around melee/unarmed fastshot where you had 10 attacks/round with supersledge/powerfist (fastshot + bonus hth attacks). With Fallout2 behavior that would be impossible.

This is obviously very subjective, how far to go with the changes/fixes etc. But there's a couple bugs/peculiarities around which entire playstyles were created. The fastshot melee I think is one, another would be the everlasting flares in Fallout2 which allows the player to go for 10 attacks/round with flares in F2.
