### ISSUE TITLE
No randomness in sneak skill?

### ISSUE THREAD

**Issue by emxd** [alexbatalov/fallout1-ce#56]
When the game is polling whether the character is sneaking, the condition there is almost always true?
https://github.com/alexbatalov/fallout1-ce/blob/406b69b0fc52b53608cc34782ca9976c8b2b9c3e/src/game/critter.cc#L1086

Also is there any randomness? I added a breakpoint on roll_random() and it was never hit for the purpose of sneaking. Or I just goofed up :)

**Comment by M1sh2** [comment]
There really is something wrong with stealth, I got through the whole game with 32% skill, and more often than not I wasn't seen. It's harder to pull this off on the original.
