### ISSUE TITLE
Minor print differences

### ISSUE THREAD

**Issue by emxd** [alexbatalov/fallout1-ce#57]
Just some cosmetic stuff.
In re/ce the attack mode with barehanded unarmed attacks/knuckles/powerfists etc. is called "Punch"
In vanilla it is "Unarmed"

Unarmed also makes it bit more sense considering that unlike Fallout2, kicks are grouped together with punches here.

And if you print the current timedate with the '/' hotkey, the formatting is a bit different between vanilla and re/ce.

**Comment by alexbatalov** [comment]
I guess your vanilla is v1.1 (which uses m/d/y format). This piece of code was updated to v1.2 (which added some localization features, which in turn made m/d/y not so obvious for European users). I've changed punctuations slightly, not sure if it was necessary.

**Comment by emxd** [comment]
I'm using this gog version https://www.gogdb.org/product/1

Which apparently uses data files from 1.2, but falloutw executable is 1.1. What a mess. Good to know.
