### ISSUE TITLE
Android - Touch areas

### ISSUE THREAD

**Issue by QrTa** [alexbatalov/fallout1-ce#6]
It look like I only can move the cursor in a vertical line at the black bars of the screen. https://user-images.githubusercontent.com/81707167/218254682-f5ea274c-3086-48df-b23c-d7fdee20982d.mp4

**Comment by alexbatalov** [comment]
You can get rid of these black bars by setting proper resolution in `f1_res.ini`. Put this file in the game folder (together with `fallout.cfg`).

Here is an example for 20:9 device:
```ini
[MAIN]
SCR_WIDTH=1067
SCR_HEIGHT=480
```

**Comment by QrTa** [comment]
> You can get rid of these black bars by setting proper resolution in `f1_res.ini`. Put this file in the game folder (together with `fallout.cfg`).
> 
> Here is an example for 20:9 device:
> ```ini
> [MAIN]
> SCR_WIDTH=1067
> SCR_HEIGHT=480
> ```
> 
> 

Thank you!

**Comment by QrTa** [comment]
One more thing, which is related to clicks. Is it possible to set 2 and 3 taps to 1 and 2? 
I mean to only tap once for left and 2 for right click.

**Comment by alexbatalov** [comment]
Mobile controls is one of the most frequent requests, there are several proposals (similar to yours) and one PR in F2CE. Will check for next release.

**Comment by QrTa** [comment]
Thank you for your time! Keep up the good work! It's awesome! 👍
