### ISSUE TITLE
Shift+a "loot all" hotkey sometimes doesn't work

### ISSUE THREAD

**Issue by emxd** [alexbatalov/fallout1-ce#60]
[SLOT09.zip](https://github.com/alexbatalov/fallout1-ce/files/10850137/SLOT09.zip)

Distribution: GOG
Behavior present in: fallout1-ce (https://github.com/alexbatalov/fallout1-ce/actions/runs/4291850450)
Platform: win11 21h2

In the savefile, I can't loot the body at my feet with the loot all hotkey. If I drop 2 weight or more (like dropping 2 throwing knives), the hotkey starts to work.

**Comment by alexbatalov** [comment]
"Take all" is an "undocumented" feature from Fallout 2. There is no button graphic and there is no appropriate error message in `inventry.msg` (31: "Sorry, you cannot carry that much."). The only way to fix it correctly is to distribute custom `.dat` file with necessary stuff. I'm studying some options to do that, but don't hold your breath yet.

**Comment by emxd** [comment]
Why is the weight limit triggered in that particular save file though? The character has plenty of space left, I thought that this is just some weight limit calculation gone wrong.

**Comment by emxd** [comment]
Isn't this also a F2 bug? Looking at the F2-ce weight calc function and it's identical to F1-ce. I think this could happen there too.

**Comment by alexbatalov** [comment]
You're right, there is a small bug in F1 - it counts your equipped items when calculating target inventory weight during looting. However it does not affect F1 gameplay since there is no "Take all" button. In F2 these functions have additional guard, which I've also copied.
