### ISSUE TITLE
Unable to run with Steam OS

### ISSUE THREAD

**Issue by cpressland** [alexbatalov/fallout1-ce#61]
Hello,

When trying to launch the Linux x64 binary on Steam OS I get the following message: "Could not find the master datafile. Please make sure the FALLOUT CD is in the drive and that you are running FALLOUT from the directory you installed it to."

![1C5TDAw](https://user-images.githubusercontent.com/6557665/221916197-23a8e37a-8f6f-473a-a441-fef1e311d8b4.png)

This is the Steam install of Fallout 1, it runs fine using proton from the Steam UI, but lacks some of the finesse this project provides.

Any help would be appreciated.

**Comment by c6-dev** [comment]
https://github.com/alexbatalov/fallout1-ce#configuration
You need to update the .cfg, or rename your files.

**Comment by cpressland** [comment]
You’re absolutely right, I just didn’t RTFM properly. I apologise, it works great on the deck!
