### ISSUE TITLE
IOS - No way to use items inside the inventory

### ISSUE THREAD

**Issue by bencarr1337** [alexbatalov/fallout1-ce#7]
On the PC version you can right click, then hold down left click on an inventory item (while inside the inventory menu) this brings up a different sub menu where you can throw/use the items.

I cant figure out how to access this sub menu on the IOS. Is it possible?

**Comment by alexbatalov** [comment]
Triple tap acts as right mouse button (switches mouse mode). Double tap and hold to bring up context menu.

**Comment by bencarr1337** [comment]
Solved, thank you.
