### ISSUE TITLE
Fallout Crashing when entering vault 15

### ISSUE THREAD

**Issue by Hoplite1111** [alexbatalov/fallout1-ce#79]
Every time I enter vault 15 my game crashes. I have restarted my computer and tried to progress more in different areas to no avail. Oddly enough it worked initially but suddenly stopped. I’m on Mac.

**Comment by ErwanHenry** [comment]
Same problem here

**Comment by Hoplite1111** [comment]
I’ve tried everything like moving older save files out of the save as well as saving to a different file and such. It’s such a shame as this is literally game breaking with the only solution I can see being to completely restart from nothing.

**Comment by emxd** [comment]
Are you using the latest build? I think this was already fixed, e.g. https://github.com/alexbatalov/fallout1-ce/issues/34

**Comment by Hoplite1111** [comment]
I just downloaded it yesterday

**Comment by c6-dev** [comment]
You probably downloaded the release version which is 4 months old. You need the latest build from Actions tab.

**Comment by Hoplite1111** [comment]
Yeah I was a bout to say I only saw 1 release which was ver 1.0 from February

**Comment by Hoplite1111** [comment]
https://github.com/alexbatalov/fallout1-ce/assets/136226630/4f648f7f-0c8c-41fc-ba5a-fcef4db1da99

**Comment by c6-dev** [comment]
You need to download the apk from [here](https://github.com/alexbatalov/fallout1-ce/actions/runs/5240940017).

**Comment by Hoplite1111** [comment]
Thank you very much good sir!
