### ISSUE TITLE
Screen fades out and never fades back in after using the first aid skill

### ISSUE THREAD

**Issue by Northfear** [alexbatalov/fallout1-ce#8]
Screen fades to black and never fades back after using the first aid. Tried with both skill and medkit item.
Reproduced on Windows 64 and my PS Vita build.
Attaching the savegame:
[SLOT01.zip](https://github.com/alexbatalov/fallout1-ce/files/10714345/SLOT01.zip)

Also that's a bit off topic, but what is the status of mod support? Mainly interested in "unofficial patch" that fixed some quests and NPC mod, but haven't had an opportunity to try them yet.

**Comment by alexbatalov** [comment]
I'm not sure which mod do you mean, but it is *expected* to work as long as it does not rely on external dependencies like Sfall.

**Comment by arrowgent** [comment]
had no issues with Doctor or First-aid fading the screen and returning
