### ISSUE TITLE
IOS Could not find master data file

### ISSUE THREAD

**Issue by ThatStr3x** [alexbatalov/fallout1-ce#9]
After installing the app on my Iphone using my pc i keep getting the error "Could not find master datafile. Please make sure the FALLOUT CD is in the drive and that you are running FALLOUT from the directory you installed it to."

**Comment by alexbatalov** [comment]
This is expected, you don't have game assets yet. See final installation step from readme:

> Use Finder (macOS Catalina and later) or iTunes (Windows and macOS Mojave or earlier) to copy `master.dat`, `critter.dat`, and `data` folder to "Fallout" app ([how-to](https://support.apple.com/HT210598)).

**Comment by zaphtark** [comment]
If you have indeed added the game assets, make sure the file names are in lowercase. That fixed it for me.

**Comment by ThatStr3x** [comment]
> If you have indeed added the game assets, make sure the file names are in lowercase. That fixed it for me.

This solved my problem. Thank you!
